#!/bin/bash
#sin

RED=$(tput setaf 1) 
GREEN=$(tput setaf 2) 


echo -e "${GREEN}"
PS3='select or "3" to exit: '
options=("bytag" "byquery" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "bytag")
            cd bin;python bytag.py
            ;;
        "byquery")
            cd bin;python byquery.py
            ;;
       
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done